services:
  postgres-db:
    image: postgres:17
    container_name: postgres_discodeit
    environment:
      POSTGRES_USER: discodeit_user
      POSTGRES_PASSWORD: discodeit1234
      POSTGRES_DB: discodeit
      TZ: Asia/Seoul
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - discodeit_db_data:/var/lib/postgresql/data

volumes:
  discodeit_db_data: