spring:
  application:
    name: discodeit

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # (create, create-drop, update, validate 등 사용 가능)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    root: info
    # JDBC 관련 로그를 DEBUG 레벨로 출력
    org.hibernate.SQL: debug
    # SQL 파라미터를 출력
    org.hibernate.orm.jdbc.bind: trace

discodeit:
  storage:
    type: local
    path: ./uploads


management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,loggers"

info:
  application:
    name: "Discodeit"
    version: 1.7.0

  environment:
    java-version: "17"
    spring-boot-version: "3.4.0"

    settings:
      datasource:
        url: "${spring.datasource.url}"
        driver: "${spring.datasource.driver-class-name}"
      jpa:
        ddl-auto: "${spring.jpa.hibernate.ddl-auto}"
      storage:
        type: "${discodeit.storage.type}"
        path: "${discodeit.storage.path}"
      multipart:
        max-file-size: "${spring.servlet.multipart.max-file-size}"
        max-request-size: "${spring.servlet.multipart.max-request-size}"

  author:
    name: "Discodeit"