spring:
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}
  sql:
    init:
      mode: never        # 첫 실행시에만 always로 설정, 이후에는 never로 변경
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
