spring:
  application:
    name: discodeit
  threads:
    virtual:
      enabled: true

logging:
  level:
    com.sprint.mission.discodeit: DEBUG

discodeit:
  repository:
    type: file   # jcf | file
    file-directory: ${DISCODEIT_DATA_DIR:.discodeit}
