spring:
  boot:
    admin:
      # 1. Admin Server의 주소 (Server의 실제 주소로 변경 필요)
      client:
        url: http://localhost:9090 # 예시
        instance:
          name: discodeit
  application:
    name: discodeit

management:
  endpoints:
    web:
      exposure:
        # 3. 모든 Actuator 엔드포인트 노출 (*) 또는 필요한 엔드포인트만 지정 (health, info 등)
        include: "*"
  endpoint:
    health:
      # 4. health 엔드포인트의 세부 정보 표시 설정 (권장)
      show-details: always

server:
  port: 9090