name: deploy.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - sprint-8

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile and test with Gradle
        run: ./gradlew test

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t image-post:latest .

      - name: Set environment variables for tagging
        run:  |
          echo "ECR_REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=${{ secrets.AWS_ECR_REPOSITORY_NAME }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Tag Docker image
        run: |
          docker tag image-post:latest ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
          docker tag image-post:latest ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{secrets.AWS_DEPLOY_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_DEPLOY_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to ECR
        run: |
          docker push ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
          docker push ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:latest

      - name: Download task definition template
        run: |
          aws ecs describe-task-definition --task-definition ${{secrets.AWS_TASK_NAME}} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: discodeit-app
          image: ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}

      - name: ECS 서비스 중지(프리티어 환경 고려)
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.AWS_ECS_CLUSTRE_NAME }} \
            --service ${{ secrets.AWS_ECS_SERVICES_NAME }} \
            --desired-count 0 

      - name: ECS 서비스 업데이트
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.AWS_ECS_CLUSTRE_NAME }} \
            --service ${{ secrets.AWS_ECS_SERVICES_NAME }} \
            --task-definition ${{ secrets.AWS_TASK_NAME }} \
            --desired-count 1 \
            --force-new-deployment 

      - name: Verify deployment status
        run:
          echo "Verifying deployment..."
          aws ecs describe-services --cluster ${{secrets.AWS_ECS_CLUSTRE_NAME}} --services ${{secrets.AWS_ECS_SERVICES_NAME}}
          echo "Deployment seems stable."